name: Build and Test 🐍 distribution 📦

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build distribution 📦
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"
      - name: Install uv
        uses: astral-sh/setup-uv@v4
      - name: Install dependencies
        run: uv sync
      - name: Lint and Typecheck
        run: make checkall
      - name: Package
        run: make packagecheck
